sudo: required
language: ruby
dist: trusty


addons:
  apt:
    sources:
       - google-chrome
    packages:
    - google-chrome-stable

rvm:
 - 2.4.2

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - bundle install
  - bundle exec chromedriver-update 2.28

script: bundle exec ruby run_test.rb

branches:
  only:
    - master
    - qa
    - staging
